version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 9000:9000

  db:
    image: mysql:8.0
    ports:
      - 13306:${DB_PORT}
    volumes:
      - ./docker/db-store:/var/lib/mysql
      - ./docker/db/etc/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      TZ: Asia/Tokyo

  db-testing:
    image: mysql:8.0
    ports:
      - 13307:${DB_PORT}
    volumes:
      - ./docker/db/etc/mysql/conf.d:/etc/mysql/conf.d
    env_file:
      - ./.env.testing
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      TZ: Asia/Tokyo

  web:
    image: nginx:1.19.2-alpine
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
      - ./docker/web/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
      - db-testing
