version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/devlog-mh
    working_dir: /var/www/devlog-mh
    environment:
      VIRTUAL_HOST: devlog-mh.com
      LETSENCRYPT_HOST: devlog-mh.com
      LETSENCRYPT_EMAIL: mh.goto.web@gmail.com

  web:
    image: nginx:1.19.2-alpine
    network_mode: bridge
    volumes:
      - .:/var/www/devlog-mh
      - ./docker/web/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
