version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html

  db:
    image: mysql:8.0
    ports:
      - 13306:3306
    volumes:
      - ./docker/db-store:/var/lib/mysql
      - ./docker/db/etc/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: devlog_mh_dev
      MYSQL_USER: root
      TZ: Asia/Tokyo

  db-testing:
    image: mysql:8.0
    ports:
      - 13307:3306
    volumes:
      - ./docker/db/etc/mysql/conf.d:/etc/mysql/conf.d
    env_file:
      - ./.env.testing
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: devlog_mh_test
      MYSQL_USER: root
      TZ: Asia/Tokyo

  web:
    image: nginx:1.19.2-alpine
    ports:
      - 8080:80
    volumes:
      - .:/usr/share/nginx/html
      - ./docker/web/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
      - db-testing
