version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-prod
    user: ${UID}:${GID}
    ports:
      - 19000:9000
    volumes:
      - .:/var/www/devlog-mh
    working_dir: /var/www/devlog-mh

  web:
    image: nginx:1.19.2-alpine
    ports:
      - 8080:80
    volumes:
      - .:/var/www/devlog-mh
      - ./docker/web/etc/nginx/conf.d/default-ssl.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/devlog-mh.com:/etc/letsencrypt/live/devlog-mh.com
      - /etc/letsencrypt/archive/devlog-mh.com:/etc/letsencrypt/archive/devlog-mh.com
    working_dir: /var/www/devlog-mh
    environment:
      VIRTUAL_HOST: devlog-mh.com
      LETSENCRYPT_HOST: devlog-mh.com
      LETSENCRYPT_EMAIL: mh.goto.web@gmail.com
    depends_on:
      - app
