version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/var/www/html
    ports:
      - 9000:9000

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker/db-store:/var/lib/mysql
      - ./docker/db/etc/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: devlog_mh

  nginx:
    image: nginx:1.19.2-alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
      - ./docker/web/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql
