version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 19000:9000
    volumes:
      - .:/var/www/devlog-mh
    working_dir: /var/www/devlog-mh

  db:
    image: mariadb:10.3
    ports:
      - 13306:3306
    volumes:
      - ./docker/db-store:/var/lib/mysql
      - ./docker/db/etc/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: devlog_mh_dev
      MYSQL_USER: root
      TZ: Asia/Tokyo

  db-testing:
    image: mariadb:10.3
    ports:
      - 13307:3306
    volumes:
      - ./docker/db/etc/mysql/conf.d:/etc/mysql/conf.d
    env_file:
      - ./.env.testing
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: devlog_mh_test
      MYSQL_USER: root
      TZ: Asia/Tokyo

  web:
    image: nginx:1.19.2-alpine
    ports:
      - 8080:80
    volumes:
      - .:/var/www/devlog-mh
      - ./docker/web/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/devlog-mh
    environment:
      VIRTUAL_HOST: devlog-mh.com
      # LETSENCRYPT_HOST: devlog-mh.com
      # LETSENCRYPT_EMAIL: mh.goto.web@gmail.com
    depends_on:
      - app
      - db
      - db-testing

networks:
  default:
    external:
      name: nginx-proxy
