version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    ports:
      - 9000:9000
    environment:
      VIRTUAL_HOST: devlog-mh.com
      LETSENCRYPT_HOST: devlog-mh.com
      LETSENCRYPT_EMAIL: mh.goto.web@gmail.com

  web:
    image: nginx:1.19.2-alpine
    volumes:
      - .:/usr/share/nginx/html
      - ./docker/web/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/web/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

networks:
  default:
    external:
      name: nginx-proxy
