version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-prod
    user: ${UID}:${GID}
    ports:
      - 19000:9000
    volumes:
      - .:/var/www/devlog-mh
      - ./docker/app/php.ini-prod:/usr/local/etc/php/php.ini
    working_dir: /var/www/devlog-mh
    networks:
      devlog-net:
        ipv4_address: 172.18.0.2

  web:
    image: nginx:1.19.2-alpine
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - .:/var/www/devlog-mh
      - ./docker/web/etc/nginx/conf.d/default-ssl.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/devlog-mh.com:/etc/letsencrypt/live/devlog-mh.com
      - /etc/letsencrypt/archive/devlog-mh.com:/etc/letsencrypt/archive/devlog-mh.com
    working_dir: /var/www/devlog-mh
    networks:
      devlog-net:
        ipv4_address: 172.18.0.3
    depends_on:
      - app

networks:
  devlog-net:
    name: devlog-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
