version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-prod
    user: ${UID}:${GID}
    ports:
      - 19000:9000
    volumes:
      - .:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html

  web:
    image: nginx:1.19.2-alpine
    ports:
      - 8080:80
    volumes:
      - .:/usr/share/nginx/html
      - ./docker/web/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /usr/share/nginx/html
    environment:
      VIRTUAL_HOST: devlog-mh.com
      LETSENCRYPT_HOST: devlog-mh.com
      LETSENCRYPT_EMAIL: mh.goto.web@gmail.com
    depends_on:
      - app

networks:
  default:
    external:
      name: nginx-proxy
