Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.33.101"
  config.vm.synced_folder "./", "/vagrant"
  config.vm.synced_folder "../src", "/home/vagrant/www.devlog-mh.com", :owner=> 'vagrant', mount_options: ['dmode=777', 'fmode=777']

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "./ansible/vagrant.yml"
  end

  config.vm.provision "reload"
end