- name: copy file ssh_config copy
  copy:
    src: ssh_config
    dest: /etc/ssh/ssh_config
    mode: 0600
    owner: root
    group: root
- name: copy file sshd_config copy
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    mode: 0600
    owner: root
    group: root
- name: restart sshd
  service:
    name: sshd
    state: restarted
    enabled: true