- name: Get NVM
  shell: 'curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash'
  become_user: vagrant

- name: Export nvm
  shell: 'echo NVM_DIR="/home/vagrant/.nvm" >> ~/.bash_profile'
  become_user: vagrant

- name: Set profile
  copy:
    src: nvm.sh
    dest: /etc/profile.d/nvm.sh

- name: Install NVM
  shell: source /etc/profile && nvm install --lts
  become_user: vagrant

- name: Use NVM
  shell: source /etc/profile && nvm use --lts
  become_user: vagrant

- name: check node_modules
  stat: path=/home/vagrant/www.devlog-mh.com/node_modules
  register: installed_node_modules
  become_user: vagrant

- name: Exe npm install
  shell: npm install
  when: installed_node_modules == false
  become_user: vagrant
